# Site settings
author: Laura Hatch
title: COVID_can't stop the learning
header-img: img/home-bg.png
email: laura.hatch.lh@gmail.com
copyright_name: Laura Hatch
description: > # this means to ignore newlines until "baseurl:"
  Flatiron_learning in the middle of  pandemic
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: LauraHatch15
github_username:  ladeeluc

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
